### ISSUE TITLE
Example project - Unable to resolve @babel/runtime (iOS)

### ISSUE THREAD

**Issue by vladimirevstratov** [baronha/react-native-photo-editor#10]
Tried to build and run project in `example` folder, but stucks after run:
 Unable to resolve module @babel/runtime/helpers/interopRequireDefault

<img width="337" alt="Снимок экрана 2021-11-28 в 20 08 09" src="https://user-images.githubusercontent.com/30527831/143778380-607ec12e-af59-4e3e-8ad6-56cfde40f8e8.png">

Even when i cleaned cache or reinstalled node_modules.

Environment:
Platform - iOS
XCode - Version 13.1
React Native - 0.64.2
npm - 8.1.4

**Comment by baronha** [comment]
try ```npm start -- --reset-cache ``` after install ```@babel/runtime```
