### ISSUE TITLE
showing only one filter(normal) for IOS 15

### ISSUE THREAD

**Issue by amartyach98** [baronha/react-native-photo-editor#15]
![Screenshot 2021-12-28 at 3 37 06 PM](https://user-images.githubusercontent.com/33714248/147555146-6b6e0b7e-5911-460e-9ec3-131d629e8bee.png)

**Comment by amartyach98** [comment]
Resolve this issue by adding LUTs bundle in project root.

**Comment by loker-global** [comment]
Thanks! @amartyach98 @baronha 
Can you please explain how to do this?

Do I have to download something, or is it already inside xCode after pod install?

**Comment by dmarselus** [comment]
> Thanks! @amartyach98 @baronha Can you please explain how to do this?
> 
> Do I have to download something, or is it already inside xCode after pod install?

@loker-global  the simplest way is to follow the sticker bundle for IOS or I here's the tutorial

1. create LUTsBundle (not LUTs.bundle) folder on the root (not the project root but ios folder)
2. download and copy every file from the default LUTS into the folder - https://github.com/baronha/react-native-photo-editor/tree/master/resources/LUTs.bundle
3. Rename the folder name from LUTsBundle into LUTs.bundle
4. open Xcode -> target your project name -> Build phases -> Copy Bundle resources -> Add LUTs.bundle
5. Rebuild
