### ISSUE TITLE
Problem facing in installation 

### ISSUE THREAD

**Issue by aloksingh0308** [baronha/react-native-photo-editor#2]
I'm getting this error while I run the command pod install in iOS folder 

[!] CocoaPods could not find compatible versions for pod "react-native-photo-editor":
  In Podfile:
    react-native-photo-editor (from `../node_modules/@baronha/react-native-photo-editor`)

Specs satisfying the `react-native-photo-editor (from `../node_modules/@baronha/react-native-photo-editor`)` dependency were found, but they required a higher minimum deployment target.

please help me 

react-native version latest
platform :ios, '11.0'

**Comment by baronha** [comment]
try edit ```platform :ios, '11.0'```  -> ```platform :ios, '12.0'``` in your Podfile.
