### ISSUE TITLE
requiresMainQueueSetup warning

### ISSUE THREAD

**Issue by kockok** [baronha/react-native-photo-editor#26]
```
Module PhotoEditor requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup`. 
In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.
```

I am seeing this warning every time the app launches, please investigate.

[This](https://github.com/facebook/react-native/issues/23755#issuecomment-474235632) seems to be a solution, but I can't find which file to edit for this library.

**Comment by maggievcody** [comment]
It worked for me to add the following to [PhotoEditor.m](https://github.com/baronha/react-native-photo-editor/blob/master/ios/PhotoEditor.m)

`+ (BOOL)requiresMainQueueSetup
{
  return NO;
}`

**Comment by maggievcody** [comment]
It worked for me to add the following to [PhotoEditor.m](https://github.com/baronha/react-native-photo-editor/blob/master/ios/PhotoEditor.m)

`+ (BOOL)requiresMainQueueSetup  
{  
  return NO;  
}  
`

**Comment by drvn-eb** [comment]
Facing the same issue one year later.
Are there any plans to add the fix suggested by @maggievcody in a future release?
