### ISSUE TITLE
Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15

### ISSUE THREAD

**Issue by wilsontwm** [baronha/react-native-photo-editor#32]
Hi, I got error on invalid Kotlin version when running `react-native run-android`

React Native version: 0.69.3

e: /Users/wilson/work/carlink/CarlinkApp/node_modules/@baronha/react-native-photo-editor/android/src/main/java/com/reactnativephotoeditor/activity/PhotoEditorActivity.kt: (105, 5): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.

**Comment by sewonist** [comment]
I have same issue. It must be origin photo library build with old Kotlin version. I try to some other react version though I cannot success build it.

**Comment by waaplog** [comment]
Hi,
Please go to the library folder on android studio and change the kotlin version to 1.6.0
gradle.properties file 
PhotoEditor_kotlinVersion=1.6.0
Good luck.

**Comment by sewonist** [comment]
Wow!! It work for me. Thanks a lot @waaplog 

I should change some code like below.

### Edit `node_modules/@baronha/react-native-photo-editor/android/gradle.properties` 
- `PhotoEditor_kotlinVersion=1.6.0`

### Edit `node_modules/@baronha/react-native-photo-editor/android/src/main/java/com/reactnativephotoeditor/PhotoEditorModule.kt`
```
private val mActivityEventListener: ActivityEventListener = object : BaseActivityEventListener() {
    override fun onActivityResult(activity: Activity, requestCode: Int, resultCode: Int, intent: Intent?) {
      if (requestCode == EDIT_SUCCESSFUL && intent != null) {
        when (resultCode) {
          ResponseCode.RESULT_OK -> {
            val path = intent.getStringExtra("path")
            promise?.resolve("file://$path")
          }
          ResponseCode.RESULT_CANCELED -> {
            promise?.reject("USER_CANCELLED", "User has cancelled", null)
          }
          ResponseCode.LOAD_IMAGE_FAILED -> {
            val path = intent.getStringExtra("path")
            promise?.reject("LOAD_IMAGE_FAILED", "Load image failed: $path", null)
          }

        }
      }
    }
  }
```

### Edit `node_modules/@baronha/react-native-photo-editor/android/src/main/AndroidManifest.xml`

```
  <application
    android:allowBackup="true"
    tools:replace="android:allowBackup"
    android:requestLegacyExternalStorage="true"
    >
```

**Comment by waaplog** [comment]
Hello,
From time to time, the servers start themselves automatically to keep the accuracy rate at 100 percent. During this reboot, tracking is temporarily suspended. This takes approximately 15-20 minutes. When the reboot is finished, the tracking starts back.
If the tracking does not starts please change to mail title to "TRACK-HELP" and mail it to us. 
Kind regards.

**Comment by wilsontwm** [comment]
Yup, it works. Thank you very much!

**Comment by MinhDuHung** [comment]
You save my life bro, keep going
