### ISSUE TITLE
Not open a local image by uri

### ISSUE THREAD

**Issue by windcloudit** [baronha/react-native-photo-editor#42]
On IOS I can not open the photo editor by .open() when I use local path URI ( it works by remote URL ) 

example: path: "file:///Users/abc/Library/Developer/CoreSimulator/Devices/EEA5C63E-7295-4A7A-B170-44827A3648C8/data/Containers/Data/Application/773955FB-5A11-4C0C-9744-C3E3DBD6AC0D/tmp/C772C64E-6113-47A3-8CCE-898E52CB0FB9.jpg"

Could you help me how to show the editor when using a URI local or captured by the camera?

**Comment by devinhadley** [comment]
How did you fix this? Having the same issue.
