### ISSUE TITLE
PhotoEditor.open() doesn't open editor on iOS but works on Android

### ISSUE THREAD

**Issue by devinhadley** [baronha/react-native-photo-editor#59]
I'm having an issue with the PhotoEditor.open() function: The function works perfectly fine on Android, but when running the same code on iOS, the function call terminates without any error messages and the editor does not open.

The image picker function (launchImageLibrary) is working correctly and providing a valid file URI on both platforms.
On Android, the image editor opens as expected after the image is selected.
On iOS, after selecting an image, the PhotoEditor.open() function gets called, but the editor doesn't open. There are no error messages or exceptions thrown, the function just terminates.

Code Sample:

```
const content = await launchImageLibrary({
    mediaType: "mixed",
    durationLimit: 15,
});

const path = content.assets[0].uri;

const Options = { path: path, stickers: [] };
const edited_path = await PhotoEditor.open(Options);
```

**Comment by devinhadley** [comment]
> You need to concat image uri with 'file://' to get it open in case of iOS. For example if the uri is like this "/private/var/mobile/Containers/Data/Application/8BF06247-0054-4801-B747-2BCD407A67A6/tmp/react-native-image-crop-picker/DE98896D-7A6E-406A-8D82-C179F39CF0E2.jpg".
> 
> then it'll fail. It should look like "file:///private/var/mobile/Containers/Data/Application/8BF06247-0054-4801-B747-2BCD407A67A6/tmp/react-native-image-crop-picker/DE98896D-7A6E-406A-8D82-C179F39CF0E2.jpg"
> 
> Moreover the editor is somehow not applying the edits in debug mode. Do test your application in release mode as well.
> 
> Hope this fix the issue you’re facing

This didn't fix the issue unfortunately.

**Comment by devinhadley** [comment]
Update: 
SDWebImage 5.11.1
 SDWebImageWebPCoder 0.8.5

Appear to be not installing correctly with pod install/update.

**Comment by alex-gale** [comment]
@devinhadley did you manage to solve this?

**Comment by benszedlmayer** [comment]
for anyone that has wandered here, I managed to get it to work by adding some timeout between picking the image and opening the editor, i assume because both of them open a modal, the editor needs to wait for the picker to be closed first
