### ISSUE TITLE
 Showing All Errors Only Undefined symbol: (extension in Accelerate):__C.vImage_Buffer.free() -> ()

### ISSUE THREAD

**Issue by grvsingh789** [baronha/react-native-photo-editor#7]
Hi, 
I am using this plugin for react native app which is used for editing image in both android and ios. It is working fine for android but for ios it is giving this error 
Showing All Errors Only
Undefined symbol: (extension in Accelerate):__C.vImage_Buffer.free() -> ()
  $defer #1 () -> () in (extension in react_native_photo_editor):__C.UIImage.resize_vI(__C.CGSize) -> __C.UIImage? in libreact-native-photo-editor.a(UIImage+ZLImageEditor.o)
ld: symbol(s) not found for architecture x86_64

I have done the setup mentioned in the doc.

**Comment by baronha** [comment]
Please check the swift version of the project. Or you can refer [here](https://developer.apple.com/forums/thread/670558)

**Comment by supersunho** [comment]
@vladimirevstratov 

I had the same error. but now, i fixed this issue.
Try this..

1. Open project with Xcode 
2. **Build Settings > Library Search Path**
3. Change 
```
"$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)"
```

 to 

```
"$(TOOLCHAIN_DIR)/usr/lib/swift-5.3/$(PLATFORM_NAME)"
```

**Comment by vladimirevstratov** [comment]
> "$(TOOLCHAIN_DIR)/usr/lib/swift-5.3/$(PLATFORM_NAME)"

Thanks, it works! Also checked this path but only for 5.0 string exist, but it was so simple ha!

**Comment by virenradadiya** [comment]
Move $(inherited) to the bottom of the list in Build Settings -> Library Search Paths

![Screenshot 2022-04-13 at 1 53 28 PM](https://user-images.githubusercontent.com/30589064/163133478-4f2cb4c7-80ee-42d9-87c3-4cda0d33580e.png)

It works for me
