### ISSUE TITLE
Hide Button

### ISSUE THREAD

**Issue by hapo-vupq** [baronha/react-native-photo-editor#9]
This is a great library. 👍 
But i need hide some button(ex: sticker,... ) non-use.
How i can do that?

Thank for reply! 😄

**Comment by baronha** [comment]
It will be in the future. Trust me!!

**Comment by hapo-vupq** [comment]
I hope it will come soon.
Thank you for the reply.

**Comment by rakshit-AR** [comment]
Is it there yet? @baronha

**Comment by sainijagjit** [comment]
any update on this ?
